---
- name: Remove Apache web server
  hosts: lab_servers
  become: yes

  vars_files:
    - vars/users.yaml

  tasks:
  - name: more complex items to add several users
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512') }}"
      comment: "{{ item.name|lower }}@{{ domain }}"
      home: "/home/{{ item.name|lower }}"
      update_password: on_create
      state: present
      append: no
    with_items:
    - "{{ users }}"


